// Actor physics velocity limits
pub const MAX_SPACESHIP_LINEAR_VELOCITY: f32 = 80.0;
pub const MAX_SPACESHIP_ANGULAR_VELOCITY: f32 = 20.0;
pub const MAX_NATEROID_LINEAR_VELOCITY: f32 = 80.0;
pub const MAX_NATEROID_ANGULAR_VELOCITY: f32 = 20.0;
pub const MAX_MISSILE_LINEAR_VELOCITY: f32 = 300.0;
pub const MAX_MISSILE_ANGULAR_VELOCITY: f32 = 20.0;
